/**
 * Measures the transparent/white padding around every product showcase picture and writes src/data/showcase-trim.ts.
 * Phones crop that padding away so the product fills the screen width. Run after adding or replacing a showcase image:
 *   node scripts/showcase-trim.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const layouts = fs.readFileSync(path.join(root, 'src/data/product-layouts.ts'), 'utf8');
const srcs = [...new Set([...layouts.matchAll(/"src": "(\/assets\/products\/[^"]*showcase[^"]*\.(?:png|jpe?g))"/g)].map((m) => m[1]))];

const out = {};
for (const src of srcs) {
  const file = path.join(root, 'public', src);
  const { width, height } = await sharp(file).metadata();
  const { info } = await sharp(file).trim({ threshold: 10 }).toBuffer({ resolveWithObject: true });
  // Keep a little air around the product.
  const pad = Math.round(Math.max(info.width, info.height) * 0.03);
  const x = Math.max(0, -info.trimOffsetLeft - pad);
  const y = Math.max(0, -info.trimOffsetTop - pad);
  const w = Math.min(width - x, info.width + 2 * pad);
  const h = Math.min(height - y, info.height + 2 * pad);
  out[src] = { width, height, x, y, w, h };
}

const body = Object.entries(out)
  .map(([k, v]) => `  '${k}': { width: ${v.width}, height: ${v.height}, x: ${v.x}, y: ${v.y}, w: ${v.w}, h: ${v.h} },`)
  .join('\n');
fs.writeFileSync(
  path.join(root, 'src/data/showcase-trim.ts'),
  `// Generated by scripts/showcase-trim.mjs – do not edit by hand.\n/** Visible box of each showcase picture inside its padded file (natural px). */\nexport interface TrimBox {\n  width: number;\n  height: number;\n  x: number;\n  y: number;\n  w: number;\n  h: number;\n}\n\nexport const showcaseTrim: Record<string, TrimBox> = {\n${body}\n};\n`,
);
console.log(`showcase-trim: ${srcs.length} pictures`);
