// Generated by scripts/showcase-trim.mjs – do not edit by hand.
/** Visible box of each showcase picture inside its padded file (natural px). */
export interface TrimBox {
  width: number;
  height: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const showcaseTrim: Record<string, TrimBox> = {
  '/assets/products/surge-protection-devices/showcase-1.png': { width: 2130, height: 1419, x: 96, y: 0, w: 1928, h: 1419 },
  '/assets/products/active-harmonic-filters/showcase-1.png': { width: 2900, height: 2629, x: 229, y: 581, w: 2556, h: 1400 },
  '/assets/products/uninterruptible-power-supplies/showcase-1.png': { width: 1051, height: 1024, x: 0, y: 131, w: 1051, h: 781 },
  '/assets/products/passive-harmonic-filters/showcase-1.png': { width: 630, height: 1022, x: 6, y: 2, w: 624, h: 1020 },
  '/assets/products/passive-harmonic-filters/showcase-2.png': { width: 702, height: 1140, x: 2, y: 3, w: 700, h: 1137 },
  '/assets/products/passive-harmonic-filters/showcase-3.png': { width: 733, height: 978, x: 0, y: 0, w: 733, h: 978 },
  '/assets/products/fire-pump-controllers/showcase-1.jpg': { width: 554, height: 1226, x: 0, y: 0, w: 554, h: 1226 },
  '/assets/products/fire-pump-controllers/showcase-2.png': { width: 1036, height: 1024, x: 160, y: 1, w: 784, h: 1013 },
  '/assets/products/fire-pump-controllers/showcase-3.png': { width: 736, height: 1130, x: 1, y: 0, w: 713, h: 1130 },
  '/assets/products/nickel-cadmium-and-lead-acid-batteries/showcase-1.png': { width: 1750, height: 1271, x: 283, y: 39, w: 1467, h: 1060 },
  '/assets/products/nickel-cadmium-and-lead-acid-batteries/showcase-2.png': { width: 1076, height: 1210, x: 5, y: 141, w: 1071, h: 1053 },
  '/assets/products/machine-health-monitoring/showcase-1.png': { width: 1712, height: 980, x: 0, y: 0, w: 1712, h: 980 },
};
